apiVersion: v1
kind: Service
metadata:
  name: youtube-app-service
  labels:
    app: youtube-app
spec:
  selector:
    app: youtube-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Si tu utilises un cloud, sinon utilise NodePort ou ClusterIP
